# 06-Lists Exercises

  1. Create a list with the integer values from one to one million. Use `min()` and `max()` to make sure your list actually starts at one and ends at one million. Also, use the `sum()` function to compute the sum of all values and `%timeit`'s execution time.
  

In [1]:
import timeit

list = range(1, 1000000 + 1)
print(min(list))
print(max(list))
print(sum(list))


cmd = 'list = range(1, 1000000 + 1); print(sum(list))'
print(timeit.timeit(cmd, number=10))

1
1000000
500000500000
500000500000
500000500000
500000500000
500000500000
500000500000
500000500000
500000500000
500000500000
500000500000
500000500000
0.34853808499999994


  2. Write a single line program that computes the sum of a range of integer values without using the `sum()` function and without using a loop.

  3. Use the `range()` function to make a list of the odd numbers from 1 to 20. **Hint** in ipython and this notebooks you can see a functions help text by executing for example `range?`

  4. Create a list of the multiples of 3 from 3 to 30. **HINT: USE A LIST COMPREHENSION**

  5. A number raised to the third power is called a cube. For example, the cube of 2 is written as `2**3` in Python. Create a list of the first 10 cubes (that is, the cube of each integer from 1 through 10).


# 07-Functions and Modules Exercises

  1. Write a function that iterates through a list and prints each value **without using a loop**. That is, write a recursive function to print the values of a list.

In [2]:
my_list = [1,2,3]

def print_each(my_list):
    print((my_list[-1]))
    my_list.remove(my_list[-1])
    if(len(my_list) > 0):
        print_each(my_list)
        
print_each(my_list)

3
2
1


In [3]:
def print_list(l, index =0):
    if index != len(l):
        print(l[index])
        print_list(l, index + 1)
        
print_list([x for x in range(3)])

0
1
2


In [4]:
print_each([1,3,5,7])

7
5
3
1


  2. Write a module `webget.py` that exposes a function to download a file from the web in case it does not exist locally already. The function shall have the following signature `download(url, to=None)` where the keyword argument `to` specifies where to save a file locally and with which name. If `to == None` then the file shall be saved in the current working directory `./` with the same name as it has at its origin. For example, calling your program as in the following

  ```python
  import webget

  url = 'http://data.kk.dk/dataset/76ecf368-bf2d-46a2-bcf8-adaf37662528/resource/9286af17-f74e-46c9-a428-9fb707542189/download/befkbhalderstatkode.csv'
  webget.download(url)
  ```

  will download the remote file to `./befkbhalderstatkode.csv`.

  Likely, you will need functions from the standard library modules `os`, and `urllib`. For example, read the doc strings for the following functions and implement the given function stub with help of them.

    * `os.path.isfile?`
    * `os.path.join?`
    * `os.path.basename?`
    * `urllib.parse?` 
    * `urllib.request.urlretrieve?`

In [15]:
# import webget

# moby_dick_url = 'http://i3.ytimg.com/vi/J---aiyznGQ/mqdefault.jpg'
# webget.download(moby_dick_url)

In [6]:
import os
import urllib.request as req
from urllib.parse import urlparse

moby_dick_url = 'http://i3.ytimg.com/vi/J---aiyznGQ/mqdefault.jpg'

def download(url, to=None):
    print('Beginning file download with urllib2...')
    req.urlretrieve(url, to)
download(moby_dick_url, "cat.jpg")

Beginning file download with urllib2...


# 08-Dictionaries


Using the `str` in `fst_paragraph`, your job is to return a `dict` containing all the words as keys, and the *number of occurrences* for each word as value. 
For instance, the word `'Ishmael'` occurs once, so a key with `'Ishmael'` is expected to contain the value `1`: `{'Ishmael': 1}`

In [27]:
fst_paragraph = '''
Call me Ishmael. Some years ago—never mind how long precisely—having
little or no money in my purse, and nothing particular to interest me on
shore, I thought I would sail about a little and see the watery part of
the world. It is a way I have of driving off the spleen and regulating
the circulation. Whenever I find myself growing grim about the mouth;
whenever it is a damp, drizzly November in my soul; whenever I find
myself involuntarily pausing before coffin warehouses, and bringing up
the rear of every funeral I meet; and especially whenever my hypos get
such an upper hand of me, that it requires a strong moral principle to
prevent me from deliberately stepping into the street, and methodically
knocking people’s hats off—then, I account it high time to get to
sea as soon as I can. This is my substitute for pistol and ball. With
a philosophical flourish Cato throws himself upon his sword; I quietly
take to the ship. There is nothing surprising in this. If they but knew
it, almost all men in their degree, some time or other, cherish very
nearly the same feelings towards the ocean with me.'''

cleaned = fst_paragraph.replace(',', '').replace('.', '').replace('\n', ' ').replace(';', '')
words = cleaned.lower().split()
#words = cleaned.upper().split()
count = {}
for word in words:
    count.setdefault(word, 0)
    count[word] += 1
count

{'call': 1,
 'me': 5,
 'ishmael': 1,
 'some': 2,
 'years': 1,
 'ago—never': 1,
 'mind': 1,
 'how': 1,
 'long': 1,
 'precisely—having': 1,
 'little': 2,
 'or': 2,
 'no': 1,
 'money': 1,
 'in': 4,
 'my': 4,
 'purse': 1,
 'and': 7,
 'nothing': 2,
 'particular': 1,
 'to': 5,
 'interest': 1,
 'on': 1,
 'shore': 1,
 'i': 9,
 'thought': 1,
 'would': 1,
 'sail': 1,
 'about': 2,
 'a': 5,
 'see': 1,
 'the': 10,
 'watery': 1,
 'part': 1,
 'of': 4,
 'world': 1,
 'it': 5,
 'is': 4,
 'way': 1,
 'have': 1,
 'driving': 1,
 'off': 1,
 'spleen': 1,
 'regulating': 1,
 'circulation': 1,
 'whenever': 4,
 'find': 2,
 'myself': 2,
 'growing': 1,
 'grim': 1,
 'mouth': 1,
 'damp': 1,
 'drizzly': 1,
 'november': 1,
 'soul': 1,
 'involuntarily': 1,
 'pausing': 1,
 'before': 1,
 'coffin': 1,
 'warehouses': 1,
 'bringing': 1,
 'up': 1,
 'rear': 1,
 'every': 1,
 'funeral': 1,
 'meet': 1,
 'especially': 1,
 'hypos': 1,
 'get': 2,
 'such': 1,
 'an': 1,
 'upper': 1,
 'hand': 1,
 'that': 1,
 'requires': 1,
 'strong': 1

# 9-CLI Programs

git-bash: python download_script.py 1 2

In [9]:
import sys

print(sys.argv[1:])

['-f', 'C:\\Users\\Andreas Heick Laptop\\AppData\\Roaming\\jupyter\\runtime\\kernel-1502d1e6-7eaa-42a7-8727-2c98d74994e1.json']


# 10-Working with Files

In [10]:
with open('download_script.py') as fp:
    print(fp.read())

import webget
import sys

urls = sys.argv[1:]
webget.download(urls)



In [11]:
import openpyxl

# created from: https://en.wikipedia.org/wiki/Iris_flower_data_set#Data_set
filename = 'iris_data.xlsx'
wb = openpyxl.load_workbook(filename)

sheet = wb.get_sheet_by_name("Fisher's Iris Data")
print(sheet.title)
print(wb.get_active_sheet())

Fisher's Iris Data
<Worksheet "Fisher's Iris Data">


C:\Users\Andreas Heick Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
  import sys
C:\Users\Andreas Heick Laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: Call to deprecated function get_active_sheet (Use the .active property).
  if __name__ == '__main__':


# 15-Intro to Numpy

### Class exercise: table
- on the above image find the 3 different slicings using only the array slicing notation

In [12]:
# the following line is jupyter notebook specific 
%matplotlib inline
import numpy as np
aaa = np.arange(10, 30).reshape(4, 5)
print(aaa[0,0])
print("----------")
print(aaa[0,1:4])
print("----------")
print(aaa[0:3,2])
print("----------")
print(aaa[0:4,1::2])
print("----------")
print(aaa[::2,4])

10
----------
[11 12 13]
----------
[12 17 22]
----------
[[11 13]
 [16 18]
 [21 23]
 [26 28]]
----------
[14 24]


### Class exercise: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [1]:
%matplotlib inline
import numpy as np
a = np.arange(0, 27).reshape((3, 3, 3)) # = (z, y, x)

print(a[1,1,0:3])
print("----------")
print(a[0:3,1,0])
print("----------")
print(a[0,:,2])

[12 13 14]
----------
[ 3 12 21]
----------
[2 5 8]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6
  - using the operators: `%` or `|` mask away both numbers that is divisible by 3 and numbers begging with 8


In [5]:
%matplotlib inline
import numpy as np
# solution:
data = np.arange(1,101).reshape(10,10)
e = data[data%2 == 0]
print(e)
print("---------")
print(data[np.where(data%10 == 6)])
print("---------")
print(data[np.where((data%3 != 0) & (data%80 > 10))])
print("---------")
# nump.masking_ex()

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
---------
[ 6 16 26 36 46 56 66 76 86 96]
---------
[ 11  13  14  16  17  19  20  22  23  25  26  28  29  31  32  34  35  37
  38  40  41  43  44  46  47  49  50  52  53  55  56  58  59  61  62  64
  65  67  68  70  71  73  74  76  77  79  91  92  94  95  97  98 100]
---------


# 16-Pandas

# Class exercise with dates
Create a function: get_meeting_dates in a module called myUtilities.py
- the function must take 3 arguments (start_date=now, period_as_timedelta, time_of_day, number_of_meetings)
- the function should then return a list of datetimes for a series of meetings that should take place from start_date and evenly distributed throughout the period.
- create another list of number of attendents, that was actually there at each meeting.
- create a bar plot of attendance through the series of meetings.

In [ ]:
%pylab inline

In [51]:
from datetime import datetime, date, time, timedelta
import numpy as np


def get_meeting_dates (period_as_timedelta, time_of_day, number_of_meetings, start_date=datetime.today()):
# Error Handling
    if number_of_meetings > period_as_timedelta.days:
        raise ValueError('Too many meetings!')
        
# day_deltas (linspace) spreads the meetings from 0 to period days -1
    day_deltas = np.linspace(0, period_as_timedelta.days - 1, number_of_meetings, dtype=int)
# define base time of day for a meeting
    base_time_of_day = datetime.combine(start_date, time_of_day)
# voodoo magic :D
    list_of_meetings = [base_time_of_day + timedelta(int(day_delta)) for day_delta in day_deltas]
    
    return list_of_meetings

get_meeting_dates(timedelta(30), time(17,0), 7)


    
    

[datetime.datetime(2019, 3, 5, 17, 0),
 datetime.datetime(2019, 3, 9, 17, 0),
 datetime.datetime(2019, 3, 14, 17, 0),
 datetime.datetime(2019, 3, 19, 17, 0),
 datetime.datetime(2019, 3, 24, 17, 0),
 datetime.datetime(2019, 3, 29, 17, 0),
 datetime.datetime(2019, 4, 3, 17, 0)]

In [78]:
import pandas as pd
df = pd.read_csv('befkbhalderstatkode.csv')
# print(df)
# print(type(df))
# print(df.columns)
# print(df.shape)
# print(type(df['ALDER']))
# print(type(df.iloc[:,0]))
# print(df['ALDER'][1])
# print(df.iloc[1][2])
df.iloc[:1][:2]

AAR  BYDEL  ALDER  STATKODE  PERSONER
0  2015      1      0      5100       614

In [81]:
import requests

# url = 'http://api.worldbank.org/v2/en/country/DNK;URY' 
# response = requests.get(url, params={'downloadformat': 'csv'})
url = 'http://api.worldbank.org/v2/en/indicator/EN.ATM.CO2E.KT?downloadformat=csv'
response = requests.get(url)

print(response.headers)

{'Date': 'Tue, 05 Mar 2019 13:41:42 GMT', 'Content-Type': 'application/zip', 'Content-Length': '75906', 'Connection': 'keep-alive', 'Content-Disposition': 'attachment; filename=API_EN.ATM.CO2E.KT_DS2_en_csv_v2_10473877.zip', 'X-Powered-By': 'ASP.NET', 'Set-Cookie': 'TS01fa65e4=01359ee9764da72eaffe9f321c78f54be6c97d71526a73e32dd29ef6dabc5de360d347df27; Path=/', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny'}


# NOTES

In [12]:
!python download_script.py 1 2

['1', '2']
